# Web Scraping Assignment with Beautiful Soup, Selenium and Exception Handling concepts

In [1]:
import warnings
warnings.simplefilter("ignore")
warnings.filterwarnings("ignore")
import requests
from bs4 import BeautifulSoup
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, ElementClickInterceptedException

Importing all the necessary dependencies here.

## Question 1

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()
driver.find_element_by_xpath("//b").click()
records = []
for row in driver.find_elements_by_xpath("(//table[@class='wikitable sortable jquery-tablesorter'])[1]//tr")[1:-1]:
    temp = ''
    for element in row.find_elements_by_xpath(".//td"):        
        temp += element.text + '|'
    records.append(temp.split('|')[:-2])

df = pd.DataFrame(records, columns=['Rank', 'Video_Name', 'Artist_Name', 'Views_in_Billions', 'Upload_Date'])

arranged_cols = ['Rank', 'Video_Name', 'Artist_Name', 'Upload_Date', 'Views_in_Billions']

df.Video_Name = df.Video_Name.apply(lambda x:x[:-4].strip('"'))
df = df[arranged_cols]
df

Legality Response number from our URL is: <Response [200]>

,Rank,Video_Name,Artist_Name,Upload_Date,Views_in_Billions
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.54
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.60
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",5.84
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.50
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.30
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.58
6,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.53
7,8.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.46
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.34
9,10.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.25
10,11.,Gangnam Style,Psy,"July 15, 2012",4.23
11,12.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.66
12,13.,Sugar,Maroon 5,"January 14, 2015",3.58
13,14.,Sorry,Justin Bieber,"October 22, 2015",3.48
14,15.,Roar,Katy Perry,"September 5, 2013",3.46
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.43
16,17.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.35
17,18.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.32
18,19.,Faded,Alan Walker,"December 3, 2015",3.17
19,20.,Dark Horse,Katy Perry,"February 20, 2014",3.17
20,21.,Girls Like You,Maroon 5,"May 31, 2018",3.16
21,22.,Lean On,Major Lazer,"March 22, 2015",3.11
22,23.,Bailando,Enrique Iglesias,"April 11, 2014",3.11
23,24.,Shake It Off,Taylor Swift,"August 18, 2014",3.11
24,25.,Let Her Go,Passenger,"July 25, 2012",3.10
25,26.,Axel F,Crazy Frog,"June 16, 2009",3.07
26,27.,Mi Gente,J Balvin,"June 29, 2017",2.99
27,28.,Perfect,Ed Sheeran,"November 9, 2017",2.99
28,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",2.98
29,30.,Hello,Adele,"October 22, 2015",2.90

## Question 2

In [3]:
url = "https://www.bcci.tv/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

btn=driver.find_element_by_xpath("//div[@class = 'navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")
driver.get(btn.get_attribute("href"))
time.sleep(3)

# Empty lists
match_title=[]
series=[]
place=[]
date=[]
matchtime=[]
datetime=[]

for i in driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__format']"):
    match_title.append(i.text)
    
for i in driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__tournament-label u-truncated']"):
    series.append(i.text)

for i in driver.find_elements_by_xpath("//div[@class='fixture__description u-unskewed-text']/p/span"):
    place.append(i.text)
    
for i in driver.find_elements_by_xpath("//div[@class='fixture__datetime desktop-only']"):
    datetime.append(i.text.replace('\n',' '))
    
date=[i.split(' ',3)[:3] for i in datetime]
date=[' '.join(i) for i in date]
matchtime=[i.split(' ',3)[-1] for i in datetime]

# Creating data frame
matches_data=pd.DataFrame({'Match Title': match_title,
                          "Series": series,
                          "Place": place,
                          "Date": date,
                          "Time": matchtime})
matches_data

Legality Response number from our URL is: <Response [200]>

,Match Title,Series,Place,Date,Time
0,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",Sunday 31 OCTOBER,19:30 IST
1,T20I,2021 ICC MEN'S T20 WORLD CUP,"Zayed Cricket Stadium, Abu Dhabi",Wednesday 03 NOVEMBER,19:30 IST
2,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",Friday 05 NOVEMBER,19:30 IST
3,T20I,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",Monday 08 NOVEMBER,19:30 IST
4,T20I,INDIA V NEW ZEALAND 2021,"Sawai Mansingh Stadium, Jaipur",Wednesday 17 NOVEMBER,NOVEMBER
5,T20I,INDIA V NEW ZEALAND 2021,"JSCA International Stadium Complex, Ranchi",Friday 19 NOVEMBER,NOVEMBER
6,T20I,INDIA V NEW ZEALAND 2021,"Eden Gardens, Kolkata",Sunday 21 NOVEMBER,NOVEMBER
7,TEST,INDIA V NEW ZEALAND 2021,"Green Park, Kanpur",Thursday 25 NOVEMBER,NOVEMBER
8,TEST,INDIA V NEW ZEALAND 2021,"Wankhede Stadium, Mumbai",Friday 03 DECEMBER,DECEMBER
9,ODI,INDIA V WEST INDIES 2022,"Narendra Modi Stadium, Ahmedabad",Sunday 06 FEBRUARY,FEBRUARY

## Question 3

In [4]:
url = "https://www.guru99.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

error = driver.find_element_by_xpath('//*[@id="java_technologies"]/li[3]/a').get_attribute('href')
driver.get(error)
time.sleep(3)
exception = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a').get_attribute('href')
driver.get(exception)

Data = []
table = driver.find_elements_by_xpath("//table[@class='table table-striped']//td")
for i in table:
    try:
        Data.append(i.text)
    except NoSuchElementException:
        Data.append('-')

Name = []
for i in range(2,len(Data),2):
    Name.append(Data[i])

Description = []
for i in range(3,len(Data),2):
    Description.append(Data[i])

df=pd.DataFrame({"Exception name": Name, "Exception description": Description})
df

Legality Response number from our URL is: <Response [200]>

,Exception name,Exception description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

## Question 4

In [11]:
url = "https://statisticstimes.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

economy = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy.click()
time.sleep(2)
india = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
india.click()
time.sleep(2)

Legality Response number from our URL is: <Response [200]>

In [12]:
ind_eco = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
ind_eco.click()
time.sleep(2)

# Empty lists
Rank = []
State = []
GSDP1 = []
GSDP2  = []
Share = []
GDP_billion = []

try: # Scraping Rank
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping Name
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping GSDP1
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping GSDP2
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException as e:
    print("-")

try: # Scraping share
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException as e:
    print("-")    
    
try: # Scraping GDP billion
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException as e:
    print("-")
    
# Creating data frame 
stats = pd.DataFrame({"Rank":Rank, "State":State, "GSDP (Cr INR at Current prices) (19-20)":GSDP1,
                      "GSDP (Cr INR at Current prices) (18-19)":GSDP2, "Share (18-19)":Share, 
                      "GDP ($ billion)":GDP_billion})
stats

,Rank,State,GSDP (Cr INR at Current prices) (19-20),GSDP (Cr INR at Current prices) (18-19),Share (18-19),GDP ($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
61,29,Sikkim,"28,391","25,141",0.15%,"17,060"
62,30,Nagaland,-,"24,534",0.15%,-
63,31,Arunachal Pradesh,-,"22,488",0.13%,-
64,32,Mizoram,"24,424","20,947",0.13%,"17,797"
65,33,Andaman & Nicobar Islands,-,-,-,-

## Question 5

In [17]:
url = "https://github.com/trending"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

Legality Response number from our URL is: <Response [200]>

In [19]:
# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

#scraping repositories urls
repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2) 

    
#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)
    

for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
    #scraping repositories discription
    try:
        repo = driver.find_element_by_xpath("/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[1]/div/p")
        repo_desc.append(repo.text)
    except NoSuchElementException:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    time.sleep(2)
    
     #scraping languages used   
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   
#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

,Title,Description,Contributors_count,Language_used
0,arco-design / arco-design,A comprehensive React UI components library,9,"[TypeScript, Less, JavaScript]"
1,DouyinFE / semi-design,"A modern, comprehensive, flexible design syste...",21,"[TypeScript, JavaScript, SCSS]"
2,devMEremenko / XcodeBenchmark,XcodeBenchmark measures the compilation time o...,52,"[Swift, Shell, Ruby]"
3,matrixorigin / matrixone,"Planet scale, cloud-edge native big data engin...",17,"[Go, Assembly]"
4,github / copilot-docs,Documentation for GitHub Copilot,3,"[Python, Ruby]"
5,nvm-sh / nvm,Node Version Manager - POSIX-compliant bash sc...,304,"[Shell, Makefile]"
6,acidanthera / OpenCorePkg,OpenCore bootloader,62,"[C, Assembly, C++]"
7,nuta / kerla,A new operating system kernel with Linux binar...,7,"[Rust, Python, Assembly, Makefile]"
8,czj2369 / jd_tb_auto,基于AutoJs编写的618||双十一||淘宝||京东||赚喵币||赚汪汪币任务自动完成脚本,No details available,[JavaScript]
9,modern-js-dev / modern.js,The meta-framework suite designed from scratch...,18,"[TypeScript, JavaScript, Handlebars, CSS, Smar..."
10,vercel / next-rsc-demo,Demo repository for Next.js + React server com...,3,[JavaScript]
11,LSPosed / MagiskOnWSA,Integrate Magisk root and OpenGApps into WSA (...,5,[No languages used]
12,jojo2234 / GreenPass-Experiments,It's possible to create a valid and fake green...,No details available,"[HTML, Kotlin, Python]"
13,stong / how-to-exploit-a-double-free,How to exploit a double free vulnerability in ...,2,"[Python, C++]"
14,mli / paper-reading,深度学习经典、新论文逐段精读,No details available,[No languages used]
15,vercel / next.js,The React Framework,"1,818","[JavaScript, TypeScript, Rust, CSS, Shell, SCSS]"
16,0voice / audio_video_streaming,音视频流媒体权威资料整理，500+份文章，论文，视频，实践项目，协议，业界大神名单。,5,[No languages used]
17,sdras / awesome-actions,A curated list of awesome actions to use on Gi...,280,[No languages used]
18,KubeOperator / KubePi,KubePi 是一款简单易用的开源 Kubernetes 可视化管理面板,7,"[Go, Vue, JavaScript, HTML, SCSS, TypeScript]"
19,smknstd / modern-php-cheatsheet,Cheatsheet for some PHP knowledge you will fre...,4,[No languages used]
20,mitchellh / nixos-config,My NixOS configurations.,2,"[Nix, Shell, Makefile, Dockerfile, Scheme]"
21,vandadnp / flutter-tips-and-tricks,A Collection of Flutter and Dart Tips and Tricks,No details available,[Dart]
22,haoziqaq / varlet,基于Vue3的Material design风格移动端组件库 Material design...,17,"[Vue, TypeScript, JavaScript, Less]"
23,cheatsheet1999 / FrontEndCollection,Notes for Front-end Software Engineers. Covers...,3,"[JavaScript, HTML, CSS]"
24,vpncn / vpncn.github.io,2021中国翻墙软件VPN推荐以及科学上网避坑，稳定好用。对比SSR机场、蓝灯、V2ray、...,No details available,[HTML]

## Question 6

In [20]:
url = "https://www.billboard.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

hot_100 = driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[2]/nav/ul/li[3]/a')
hot_100.click()
time.sleep(2)

Song_name=[i.text for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__song text--truncate color--primary']")]

Artist_name=[i.text for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__artist text--truncate color--secondary']")]

Last_week_rank=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--last']")]

Peak_rank=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--peak']")]

Weeks_on_board=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--week']")]

# Creating data frame
Songs=pd.DataFrame({"SONG NAME":Song_name, "ARTIST":Artist_name, "LAST WEEK RANK":Last_week_rank,
                    "PEAK RANK":Peak_rank, "WEEK ON BORD":Weeks_on_board})
Songs

Legality Response number from our URL is: <Response [200]>

,SONG NAME,ARTIST,LAST WEEK RANK,PEAK RANK,WEEK ON BORD
0,Easy On Me,Adele,68,1,2
1,Stay,The Kid LAROI & Justin Bieber,2,1,15
2,Industry Baby,Lil Nas X & Jack Harlow,1,1,13
3,Fancy Like,Walker Hayes,3,3,18
4,Bad Habits,Ed Sheeran,4,2,17
...,...,...,...,...,...
95,Who's In Your Head,Jonas Brothers,95,95,2
96,Woo Baby,Pop Smoke Featuring Chris Brown,92,64,3
97,Flocky Flocky,Don Toliver Featuring Travis Scott,53,53,2
98,Like A Lady,Lady A,90,90,2
99,Just About Over You,Priscilla Block,97,97,2

## Question 7

In [21]:
url = "https://www.naukri.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

rec = driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/ul[1]/li[2]/a/div').click()
driver.switch_to_window(driver.window_handles[1]) # switching window to make the main window as primary
search = driver.find_element_by_xpath("//div[@class='inpWrap']/input")
search.send_keys('Data Science')
search_btn = driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()

name = []
designation = []
company = []
skills = []
location = []

# fetching Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    name.append(i.text)
    
# fetching Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    designation.append(i.text)

# fetching Company names
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    company.append(i.text)
    
# fetching  Skills
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        skills.append(i.text)
    except NoSuchElementException:
        skills.append('-')
                
# fetching Locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):
    location.append(i.text)
    
# Creating a dataframe
data = list(zip(name, designation, company, skills, location))
df = pd.DataFrame(data, columns = ["Name", "Designation", "Company Name", "Skills they hire for", "Location"])
df

Legality Response number from our URL is: <Response [200]>

,Name,Designation,Company Name,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,MARSIAN Technologies LLP
7,Narasimha,Company Recruiter,Step Next Private Limited,"Data Modeling, Data Wrangling, seaborn, eda, p...",Company HR
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Pune
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Anik Agrawal
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Company Recruiter
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions Pvt.Ltd.,"Oracle Dba, Data Science, Data Warehousing, ET...",Ahmedabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",subhas patel
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Founder CEO
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",UK - (london)
15,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Abhishek - Only Analytics Hiring - India and
16,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Recruitment Lead Consultant
17,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Vadodara / Baroda
18,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Narasimha
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Company Recruiter
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Hyderabad / Secunderabad
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Balu Ramesh
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",HR Administrator
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Trivandrum
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Asif Lucknowi
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Director
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Indore
30,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",InstaFinancials
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Human Resource
32,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
33,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Priyanka Akiri
34,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Walmart Interra Skeps Expressstores indifi whi...,HR Manager
35,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Hyderabad
36,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Kalpana Dumpala
37,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Executive Hiring
38,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Hyderabad / Secunderabad
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Mubarak
40,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Company HR
41,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
42,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Kushal Rastogi
43,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Company HR
44,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Mumbai
45,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Sandhya Khandagale
46,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",HR Recruiter
47,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Pune
48,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Ruchi Dhote
49,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Senior Executive Talent Acquisition

## Question 8

In [22]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

Book_name = []
Author_name = []
Volume_sold = []
Publisher = []
Genre = []

try: # Scraping Book name
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[2]"):
        Book_name.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Author name
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[3]"):
        Author_name.append(i.text)
except NoSuchElementException as e:
    print("-")
        
try: # Scraping Volume sold
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[4]"):
        Volume_sold.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Publisher
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[5]"):
        Publisher.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
try: # Scraping Genre
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[6]"):
        Genre.append(i.text)
except NoSuchElementException as e:
    print("-")
    
# Creating data frame 
Books=pd.DataFrame({'Book Name': Book_name, 'Author Name': Author_name, 'Volume Sold': Volume_sold,
                    'Publisher': Publisher, 'Genre' : Genre})
Books

Legality Response number from our URL is: <Response [200]>

,Book Name,Author Name,Volume Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

## Question 9

In [23]:
url = "https://www.imdb.com/list/ls095964455/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('chromedriver.exe')
driver.get(url)
driver.maximize_window()

name = []
year = []
genre = []
runtime = []
rating = []
vote = []

try: # Scraping Name
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
        name.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Year span
    for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
        year.append(i.text)
except NoSuchElementException as e:
    print("-")
        
try: # Scraping Genre
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[5]"):
        genre.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Run time
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[3]"):
        runtime.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
try: # Scraping Ratings
    for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]"):
        rating.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping votes
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]/span[2]"):
        vote.append(i.text)
except NoSuchElementException as e:
    print("-")

# Creating a dataframe 
imdb=pd.DataFrame({'Name':name, 'Year Span':year, 'Genre':genre, 'Run Time':runtime, 'Ratings':rating, 'Votes':vote})
imdb

Legality Response number from our URL is: <Response [200]>

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,890,724"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"922,835"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"908,701"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"271,949"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"232,313"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"46,156"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,994"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"178,668"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"37,322"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"208,449"

## Question 10

In [25]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

#clicking show all datasets link
show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()
time.sleep(1)


#scraping dataset names
name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping data type
data_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in info[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping dataset names
default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping dataset names
attr_type=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in info[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset names
no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset names
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset names
year=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in info[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021